[project]
name = "evidence-table"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.3.2",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "ruff>=0.8.2",
]
